import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Sidebar from "@/components/Sidebar";
import BarbedWire from "@/components/BarbedWire";
import {
  Fira_Mono,
  VT323,
  Press_Start_2P,
  Stalinist_One,
  Special_Elite,
  Share_Tech_Mono,
  Roboto_Mono,
} from "next/font/google";

export const firamono = Fira_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // 👈 include the available weights
  variable: "--font-firamono",
});

export const vt323 = VT323({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-vt323",
});

export const pressstart2p = Press_Start_2P({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pressstart2p",
});

export const stalinistone = Stalinist_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-stalinistone",
});

export const specialelite = Special_Elite({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-specialelite",
});

export const sharetechmono = Share_Tech_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sharetechmono",
});

export const robotomono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-robotomono",
});

export const metadata: Metadata = {
  title: "Zone Survival Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firamono.variable} ${vt323.variable} ${pressstart2p.variable} ${stalinistone.variable} ${specialelite.variable} ${sharetechmono.variable} ${robotomono.variable} antialiased relative min-h-screen`}
      >
        {/* Content */}
        <Header />

        <BarbedWire />
        <main className="relative z-10 flex bg-[url('/main-theme-1920.webp')] bg-cover bg-center w-full h-full min-h-[80vh]">
          {/* Sidebar */}
          <section className="w-64 shrink-0 mt-4 ml-2">
            <Sidebar />
          </section>

          {/* Page content */}
          <div className="flex-1 px-6">{children}</div>
        </main>
        <BarbedWire />
        <footer>Faraz</footer>
      </body>
    </html>
  );
}
